#!/usr/bin/env bash
# Regenerate book/overlay.ttl from every submitted transactions/2026/**
# archive entry. Re-run after archiving new transactions.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tx_root="$repo_root/transactions/2026"
out="$repo_root/book/overlay.ttl"

turtle_escape() {
  # Escape backslash and double-quote for a Turtle string literal.
  sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

slug() {
  # txid -> short slug used in node names (first 12 hex chars).
  printf '%s' "${1:0:12}"
}

emit_signer() {
  local hash="$1"
  if [ -z "$hash" ]; then return 0; fi
  cat <<EOF
<urn:cardano:id:key:$hash>
  a book:Signer .

EOF
}

emit_address() {
  local bech32="$1" label="$2"
  if [ -z "$bech32" ]; then return 0; fi
  cat <<EOF
<urn:cardano:id:address:$bech32>
  a book:Address ;
  rdfs:label "$(printf '%s' "$label" | turtle_escape)" ;
  cardano:bech32 "$bech32" .

EOF
}

{
  cat <<'EOF'
@prefix cardano: <https://lambdasistemi.github.io/cardano-ledger-rdf/vocab/cardano#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix book: <https://lambdasistemi.github.io/amaru-treasury-tx/book#> .

# Generated by book/generate.sh from transactions/2026/**.
# Do not hand-edit -- re-run generate.sh after archiving new transactions.

book:Transaction a rdfs:Class ; rdfs:label "Amaru treasury transaction (2026)" .
book:Address a rdfs:Class ; rdfs:label "Amaru treasury wallet/beneficiary address" .
book:Signer a rdfs:Class ; rdfs:label "Amaru treasury signer key" .

book:txid a rdf:Property ; rdfs:label "Transaction id" .
book:scope a rdf:Property ; rdfs:label "Treasury scope" .
book:action a rdf:Property ; rdfs:label "Action" .
book:description a rdf:Property ; rdfs:label "Description" .
book:justification a rdf:Property ; rdfs:label "Justification" .
book:destinationLabel a rdf:Property ; rdfs:label "Destination label" .
book:wallet a rdf:Property ; rdfs:label "Operator wallet" .
book:beneficiary a rdf:Property ; rdfs:label "Beneficiary / counterpart address" .
book:amount a rdf:Property ; rdfs:label "Amount" .
book:unit a rdf:Property ; rdfs:label "Unit" .
book:signer a rdf:Property ; rdfs:label "Required signer" .
book:block a rdf:Property ; rdfs:label "Block hash" .
book:slot a rdf:Property ; rdfs:label "Slot" .
book:submittedAt a rdf:Property ; rdfs:label "Submitted at" .
book:feeLovelace a rdf:Property ; rdfs:label "Fee (lovelace)" .

EOF

  find "$tx_root" -mindepth 2 -maxdepth 2 -type d | sort | while read -r dir; do
    submitted="$dir/submitted.json"
    [ -f "$submitted" ] || continue

    scope="$(basename "$(dirname "$dir")")"
    txid="$(basename "$dir")"
    s="$(slug "$txid")"

    # submitted.json ships at least two schemas: the full node-observed
    # receipt (txid/block/slot/timestamp/fee_lovelace) and a leaner
    # pre-confirmation record (txId/submittedAt, no block/slot/fee) used
    # by some reorganize-batch and disburse archives.
    txid_j="$(jq -r '.txid // .txId // ""' "$submitted")"
    block="$(jq -r '.block // ""' "$submitted")"
    slot="$(jq -r '.slot // empty' "$submitted")"
    submitted_at="$(jq -r '.timestamp // .submittedAt // ""' "$submitted")"
    fee="$(jq -r '.fee_lovelace // empty' "$submitted")"

    intent="$dir/intent.json"
    summary="$dir/summary.md"

    if [ -f "$intent" ]; then
      action="$(jq -r '.action' "$intent")"
      description="$(jq -r '.rationale.description // ""' "$intent")"
      justification="$(jq -r '.rationale.justification // ""' "$intent")"
      destination_label="$(jq -r '.rationale.destinationLabel // ""' "$intent")"
      wallet_addr="$(jq -r '.wallet.address // ""' "$intent")"
      signers="$(jq -r '.signers[]? // empty' "$intent")"

      case "$action" in
        disburse)
          beneficiary_addr="$(jq -r '.disburse.beneficiaryAddress // ""' "$intent")"
          amount="$(jq -r '.disburse.amount // empty' "$intent")"
          unit="$(jq -r '.disburse.unit // ""' "$intent")"
          ;;
        swap)
          beneficiary_addr="$(jq -r '.swap.swapOrderAddress // ""' "$intent")"
          amount="$(jq -r '.swap.amountLovelace // empty' "$intent")"
          unit="lovelace"
          ;;
        *)
          beneficiary_addr=""
          amount=""
          unit=""
          ;;
      esac
    else
      # No intent.json archived (pre-intent swap-cancel / swap-rerate flows) --
      # fall back to the human-written summary.md.
      action="$(grep -m1 -oP '(?<=\*\*Action\*\*: )\S+' "$summary" 2>/dev/null || true)"
      description="$(sed -n '1{s/^# //;p}' "$summary" 2>/dev/null || true)"
      justification=""
      destination_label=""
      wallet_addr=""
      beneficiary_addr=""
      amount=""
      unit=""
      signers="$(grep -oP '(?<=- `)[0-9a-f]{56}(?=`)' "$summary" 2>/dev/null || true)"
    fi

    {
      echo "book:tx-$s"
      echo "  a book:Transaction ;"
      echo "  rdfs:label \"$(printf '%s: %s (%s)' "$scope" "$action" "${txid:0:12}" | turtle_escape)\" ;"
      echo "  book:txid \"$txid_j\" ;"
      echo "  book:scope \"$(printf '%s' "$scope" | turtle_escape)\" ;"
      echo "  book:action \"$(printf '%s' "$action" | turtle_escape)\" ;"
      if [ -n "$description" ]; then echo "  book:description \"$(printf '%s' "$description" | turtle_escape)\" ;"; fi
      if [ -n "$justification" ]; then echo "  book:justification \"$(printf '%s' "$justification" | turtle_escape)\" ;"; fi
      if [ -n "$destination_label" ]; then echo "  book:destinationLabel \"$(printf '%s' "$destination_label" | turtle_escape)\" ;"; fi
      if [ -n "$wallet_addr" ]; then echo "  book:wallet <urn:cardano:id:address:$wallet_addr> ;"; fi
      if [ -n "$beneficiary_addr" ]; then echo "  book:beneficiary <urn:cardano:id:address:$beneficiary_addr> ;"; fi
      if [ -n "$amount" ]; then echo "  book:amount \"$amount\"^^xsd:integer ;"; fi
      if [ -n "$unit" ]; then echo "  book:unit \"$(printf '%s' "$unit" | turtle_escape)\" ;"; fi
      while IFS= read -r h; do
        if [ -n "$h" ]; then echo "  book:signer <urn:cardano:id:key:$h> ;"; fi
      done <<< "$signers"
      if [ -n "$block" ]; then echo "  book:block \"$block\" ;"; fi
      if [ -n "$slot" ]; then echo "  book:slot \"$slot\"^^xsd:integer ;"; fi
      if [ -n "$fee" ]; then echo "  book:feeLovelace \"$fee\"^^xsd:integer ;"; fi
      echo "  book:submittedAt \"$submitted_at\"^^xsd:dateTime ."
      echo
    }

    if [ -n "$wallet_addr" ]; then emit_address "$wallet_addr" "$scope operator wallet"; fi
    if [ -n "$beneficiary_addr" ]; then emit_address "$beneficiary_addr" "$scope $action counterpart address"; fi
    while IFS= read -r h; do
      if [ -n "$h" ]; then emit_signer "$h"; fi
    done <<< "$signers"
  done
} > "$out"

echo "wrote $out"
